connecting all ci pieces, including the local tool to reproduce travis actions. entry point fix still not tested. maybe we can use the scratch version after this?

diff --git a/_script/build b/_script/build
--- a/_script/build
+++ b/_script/build
@@ -3,15 +3,7 @@
 set -exuo pipefail
 cd $(dirname $0)/..
 
-function go_version_check {
-	go_version=$(go version  | cut -d " " -f 3)
-	supported_go_version="go1.9"
-	if $(test "$go_version" != "$supported_go_version") 
-	then
-		echo "ERROR: Unsupported go environment. You should use: $supported_go_version"
-		exit 1
-	fi
-}
+source _script/go_version
 
 function binary_compilation {
 	# mix of:
@@ -25,15 +17,17 @@ function binary_compilation {
 }
 
 function docker_build {
-	# TODO: this should not be static. We should pick this from somewhere, and reuse in the deploy stage"
-	tag="dachad/tcpgoon"
+	tag=$1
 	docker build -t $tag .
 }
 
 # main()
+docker_name=${1:-"dachad/tcpgoon"}
 go_version_check
-
+if $(test $? -ne 0)
+then
+	echo "ERROR: Unsupported go environment"
+	exit 1
+fi
 binary_compilation
-
-docker_build
-
+docker_build "${docker_name}"
