docker push with versioned tags introduced

diff --git a/_script/cibuild-docker b/_script/cibuild-docker
--- a/_script/cibuild-docker
+++ b/_script/cibuild-docker
@@ -38,11 +38,20 @@ function arguments_mgmt() {
 }
 
 function travis_deploy_flags() {
-    exec_env_vars=""
+    docker_deploy_flags=""
     if $(test "$sim_deploy" = "yes")
     then
-        echo "INFO: deploy flag enabled. We will enable the env variables to simulate a travis merge to master"
-        exec_env_vars='-e TRAVIS_PULL_REQUEST="false" -e TRAVIS_BRANCH="master"'
+        echo "INFO: deploy flag enabled. We will activate the env variables, and mount your docker config/credentials,\
+         to simulate a travis merge to master"
+        local_docker_config_store="${HOME}/.docker"
+        if ! $(test -f "${local_docker_config_store}/config.json")
+        then
+            echo "ERROR: You need a valid docker config credentials file in your ${local_docker_config_store} directory\
+             in order to deploy new images, with read access to the user $travis (uid 2000 in the container). \
+             You can generate it using docker login"
+            exit 1
+        fi
+        docker_deploy_flags="-v ${local_docker_config_store}:${travis_home}/.docker -e TRAVIS_PULL_REQUEST=false -e TRAVIS_BRANCH=master"
     fi
 }
 
@@ -52,14 +61,14 @@ function docker_run_cmdline_generator() {
     test_docker_image="travisci/ci-garnet:packer-1503972846"
     travis_home="/home/travis"
     travis_user="travis"
-    travis_go_version=$(cat .travis.yml | grep "^go:" -A1 | grep "^- " | cut -d " " -f 2)
+    travis_deploy_flags
     docker_mounted_project="${travis_home}/gopath/src/github.com/dachad/tcpgoon"
     http_proxy="${http_proxy:-}"
     cmdline="docker run -t -i -v $PWD:$docker_mounted_project \
             -w $docker_mounted_project \
             --user $travis_user
             -e http_proxy=$http_proxy \
-            $exec_env_vars \
+            $docker_deploy_flags \
             --privileged \
             --rm $test_docker_image \
             /bin/bash --login -c _script/$script_name"
@@ -67,7 +76,6 @@ function docker_run_cmdline_generator() {
 
 # main()
 arguments_mgmt "$@"
-travis_deploy_flags
 docker_run_cmdline_generator
 
 echo "DEBUG: executing $cmdline"
diff --git a/_script/deploy b/_script/deploy
--- a/_script/deploy
+++ b/_script/deploy
@@ -3,6 +3,39 @@
 set -exuo pipefail
 cd $(dirname $0)/..
 
+function docker_authenticate() {
+    DOCKER_USERNAME=${DOCKER_USERNAME:-""}
+    DOCKER_PASSWORD=${DOCKER_PASSWORD:-""}
+    if $(test "$DOCKER_USERNAME" != "" ) && $(test "$DOCKER_PASSWORD" != "")
+    then
+        echo "INFO: Docker env variables set. Logging in"
+        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
+        return $?
+    fi
+    local_docker_config_store="${HOME}/.docker"
+    if $(test -f "${local_docker_config_store}/config.json") && $(test -r "${local_docker_config_store}/config.json")
+    then
+        echo "INFO: Valid docker credentials file found. We will try to use it"
+        return 0
+    fi
+    echo "ERROR: No credentials in environment variables found neither a valid docker config file"
+    exit 1
+}
+
+function docker_tag() {
+    extra_docker_tag="${docker_name}:$(git log -1 --pretty=%h)"
+    sg $execgroup "docker tag $docker_name $extra_docker_tag"
+}
+
+function docker_push() {
+    sg $execgroup "docker push $extra_docker_tag"
+    sg $execgroup "docker push $docker_name"
+}
+
+
+#main()
+docker_authenticate
 docker_name=${1:-"dachad/tcpgoon"}
 execgroup="docker"
-sg $execgroup "docker push $docker_name"
+docker_tag
+docker_push
