the whole test flow looks working, also in the local travis worker emulator

diff --git a/_script/requirements b/_script/requirements
--- a/_script/requirements
+++ b/_script/requirements
@@ -3,21 +3,27 @@
 # only wants to act inside an specific travis environment.
 # We don't currently want to touch your environment
 
-set -xuo pipefail
-cd $(dirname $0)/..
 
+cd $(dirname $0)/..
 source _script/go_version
+# We avoid -e as we want to act in case of return codes different from 0
+set -xuo pipefail
 
 function upgrade_go_using_gimme() {
     GIMME_OUTPUT=$(gimme $go_version_in_travis_yml) && eval "$GIMME_OUTPUT"
 }
 
 function install_go_dependencies() {
+    echo "INFO: Installing go dependencies"
     go get ./...
 }
 
+function prepare_gopath_dir_permissions() {
+    echo "INFO: preparing gopath folder permissions"
+    sudo chown travis /home/travis/gopath/src/github.com
+}
 # main()
-if $(test "$PWD" != "/home/travis/gopath/src/github.com/dachad/tcpgoon"); then exit 0; fi
+if $(test "$PWD" != "/home/travis/gopath/src/github.com/dachad/tcpgoon"); then return 0; fi
 
 echo "INFO: looks I'm running inside the box emulating travis. I will act"
 go_version_check
@@ -27,4 +33,5 @@ then
     echo "INFO: I will try to upgrade to the one travis should use"
     upgrade_go_using_gimme
 fi
+prepare_gopath_dir_permissions
 install_go_dependencies
